// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBtoMapperQMsg.proto

package gmapper.logic;

public final class ProtobuftoMapperQMsg {
  private ProtobuftoMapperQMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ToMapperQMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 mapperId = 4;
    /**
     * <code>required int32 mapperId = 4;</code>
     */
    boolean hasMapperId();
    /**
     * <code>required int32 mapperId = 4;</code>
     */
    int getMapperId();

    // repeated string field_name = 5;
    /**
     * <code>repeated string field_name = 5;</code>
     */
    java.util.List<java.lang.String>
    getFieldNameList();
    /**
     * <code>repeated string field_name = 5;</code>
     */
    int getFieldNameCount();
    /**
     * <code>repeated string field_name = 5;</code>
     */
    java.lang.String getFieldName(int index);
    /**
     * <code>repeated string field_name = 5;</code>
     */
    com.google.protobuf.ByteString
        getFieldNameBytes(int index);

    // repeated string field_value = 6;
    /**
     * <code>repeated string field_value = 6;</code>
     */
    java.util.List<java.lang.String>
    getFieldValueList();
    /**
     * <code>repeated string field_value = 6;</code>
     */
    int getFieldValueCount();
    /**
     * <code>repeated string field_value = 6;</code>
     */
    java.lang.String getFieldValue(int index);
    /**
     * <code>repeated string field_value = 6;</code>
     */
    com.google.protobuf.ByteString
        getFieldValueBytes(int index);

    // repeated string field_type = 7;
    /**
     * <code>repeated string field_type = 7;</code>
     */
    java.util.List<java.lang.String>
    getFieldTypeList();
    /**
     * <code>repeated string field_type = 7;</code>
     */
    int getFieldTypeCount();
    /**
     * <code>repeated string field_type = 7;</code>
     */
    java.lang.String getFieldType(int index);
    /**
     * <code>repeated string field_type = 7;</code>
     */
    com.google.protobuf.ByteString
        getFieldTypeBytes(int index);
  }
  /**
   * Protobuf type {@code gmapper.logic.ToMapperQMsg}
   */
  public static final class ToMapperQMsg extends
      com.google.protobuf.GeneratedMessage
      implements ToMapperQMsgOrBuilder {
    // Use ToMapperQMsg.newBuilder() to construct.
    private ToMapperQMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ToMapperQMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ToMapperQMsg defaultInstance;
    public static ToMapperQMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ToMapperQMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ToMapperQMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000001;
              mapperId_ = input.readInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                fieldName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              fieldName_.add(input.readBytes());
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                fieldValue_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              fieldValue_.add(input.readBytes());
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                fieldType_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              fieldType_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          fieldName_ = new com.google.protobuf.UnmodifiableLazyStringList(fieldName_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          fieldValue_ = new com.google.protobuf.UnmodifiableLazyStringList(fieldValue_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          fieldType_ = new com.google.protobuf.UnmodifiableLazyStringList(fieldType_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gmapper.logic.ProtobuftoMapperQMsg.internal_static_gmapper_logic_ToMapperQMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gmapper.logic.ProtobuftoMapperQMsg.internal_static_gmapper_logic_ToMapperQMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg.class, gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ToMapperQMsg> PARSER =
        new com.google.protobuf.AbstractParser<ToMapperQMsg>() {
      public ToMapperQMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ToMapperQMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ToMapperQMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 mapperId = 4;
    public static final int MAPPERID_FIELD_NUMBER = 4;
    private int mapperId_;
    /**
     * <code>required int32 mapperId = 4;</code>
     */
    public boolean hasMapperId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 mapperId = 4;</code>
     */
    public int getMapperId() {
      return mapperId_;
    }

    // repeated string field_name = 5;
    public static final int FIELD_NAME_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList fieldName_;
    /**
     * <code>repeated string field_name = 5;</code>
     */
    public java.util.List<java.lang.String>
        getFieldNameList() {
      return fieldName_;
    }
    /**
     * <code>repeated string field_name = 5;</code>
     */
    public int getFieldNameCount() {
      return fieldName_.size();
    }
    /**
     * <code>repeated string field_name = 5;</code>
     */
    public java.lang.String getFieldName(int index) {
      return fieldName_.get(index);
    }
    /**
     * <code>repeated string field_name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFieldNameBytes(int index) {
      return fieldName_.getByteString(index);
    }

    // repeated string field_value = 6;
    public static final int FIELD_VALUE_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList fieldValue_;
    /**
     * <code>repeated string field_value = 6;</code>
     */
    public java.util.List<java.lang.String>
        getFieldValueList() {
      return fieldValue_;
    }
    /**
     * <code>repeated string field_value = 6;</code>
     */
    public int getFieldValueCount() {
      return fieldValue_.size();
    }
    /**
     * <code>repeated string field_value = 6;</code>
     */
    public java.lang.String getFieldValue(int index) {
      return fieldValue_.get(index);
    }
    /**
     * <code>repeated string field_value = 6;</code>
     */
    public com.google.protobuf.ByteString
        getFieldValueBytes(int index) {
      return fieldValue_.getByteString(index);
    }

    // repeated string field_type = 7;
    public static final int FIELD_TYPE_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList fieldType_;
    /**
     * <code>repeated string field_type = 7;</code>
     */
    public java.util.List<java.lang.String>
        getFieldTypeList() {
      return fieldType_;
    }
    /**
     * <code>repeated string field_type = 7;</code>
     */
    public int getFieldTypeCount() {
      return fieldType_.size();
    }
    /**
     * <code>repeated string field_type = 7;</code>
     */
    public java.lang.String getFieldType(int index) {
      return fieldType_.get(index);
    }
    /**
     * <code>repeated string field_type = 7;</code>
     */
    public com.google.protobuf.ByteString
        getFieldTypeBytes(int index) {
      return fieldType_.getByteString(index);
    }

    private void initFields() {
      mapperId_ = 0;
      fieldName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      fieldValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      fieldType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMapperId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(4, mapperId_);
      }
      for (int i = 0; i < fieldName_.size(); i++) {
        output.writeBytes(5, fieldName_.getByteString(i));
      }
      for (int i = 0; i < fieldValue_.size(); i++) {
        output.writeBytes(6, fieldValue_.getByteString(i));
      }
      for (int i = 0; i < fieldType_.size(); i++) {
        output.writeBytes(7, fieldType_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, mapperId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fieldName_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(fieldName_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFieldNameList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fieldValue_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(fieldValue_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFieldValueList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fieldType_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(fieldType_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFieldTypeList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gmapper.logic.ToMapperQMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gmapper.logic.ProtobuftoMapperQMsg.internal_static_gmapper_logic_ToMapperQMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gmapper.logic.ProtobuftoMapperQMsg.internal_static_gmapper_logic_ToMapperQMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg.class, gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg.Builder.class);
      }

      // Construct using gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mapperId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        fieldName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        fieldValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        fieldType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gmapper.logic.ProtobuftoMapperQMsg.internal_static_gmapper_logic_ToMapperQMsg_descriptor;
      }

      public gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg getDefaultInstanceForType() {
        return gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg.getDefaultInstance();
      }

      public gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg build() {
        gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg buildPartial() {
        gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg result = new gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mapperId_ = mapperId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          fieldName_ = new com.google.protobuf.UnmodifiableLazyStringList(
              fieldName_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.fieldName_ = fieldName_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          fieldValue_ = new com.google.protobuf.UnmodifiableLazyStringList(
              fieldValue_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.fieldValue_ = fieldValue_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          fieldType_ = new com.google.protobuf.UnmodifiableLazyStringList(
              fieldType_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.fieldType_ = fieldType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg) {
          return mergeFrom((gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg other) {
        if (other == gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg.getDefaultInstance()) return this;
        if (other.hasMapperId()) {
          setMapperId(other.getMapperId());
        }
        if (!other.fieldName_.isEmpty()) {
          if (fieldName_.isEmpty()) {
            fieldName_ = other.fieldName_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFieldNameIsMutable();
            fieldName_.addAll(other.fieldName_);
          }
          onChanged();
        }
        if (!other.fieldValue_.isEmpty()) {
          if (fieldValue_.isEmpty()) {
            fieldValue_ = other.fieldValue_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureFieldValueIsMutable();
            fieldValue_.addAll(other.fieldValue_);
          }
          onChanged();
        }
        if (!other.fieldType_.isEmpty()) {
          if (fieldType_.isEmpty()) {
            fieldType_ = other.fieldType_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureFieldTypeIsMutable();
            fieldType_.addAll(other.fieldType_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMapperId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gmapper.logic.ProtobuftoMapperQMsg.ToMapperQMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 mapperId = 4;
      private int mapperId_ ;
      /**
       * <code>required int32 mapperId = 4;</code>
       */
      public boolean hasMapperId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 mapperId = 4;</code>
       */
      public int getMapperId() {
        return mapperId_;
      }
      /**
       * <code>required int32 mapperId = 4;</code>
       */
      public Builder setMapperId(int value) {
        bitField0_ |= 0x00000001;
        mapperId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 mapperId = 4;</code>
       */
      public Builder clearMapperId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mapperId_ = 0;
        onChanged();
        return this;
      }

      // repeated string field_name = 5;
      private com.google.protobuf.LazyStringList fieldName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFieldNameIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          fieldName_ = new com.google.protobuf.LazyStringArrayList(fieldName_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public java.util.List<java.lang.String>
          getFieldNameList() {
        return java.util.Collections.unmodifiableList(fieldName_);
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public int getFieldNameCount() {
        return fieldName_.size();
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public java.lang.String getFieldName(int index) {
        return fieldName_.get(index);
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFieldNameBytes(int index) {
        return fieldName_.getByteString(index);
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public Builder setFieldName(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldNameIsMutable();
        fieldName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public Builder addFieldName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldNameIsMutable();
        fieldName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public Builder addAllFieldName(
          java.lang.Iterable<java.lang.String> values) {
        ensureFieldNameIsMutable();
        super.addAll(values, fieldName_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public Builder clearFieldName() {
        fieldName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_name = 5;</code>
       */
      public Builder addFieldNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldNameIsMutable();
        fieldName_.add(value);
        onChanged();
        return this;
      }

      // repeated string field_value = 6;
      private com.google.protobuf.LazyStringList fieldValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFieldValueIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          fieldValue_ = new com.google.protobuf.LazyStringArrayList(fieldValue_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public java.util.List<java.lang.String>
          getFieldValueList() {
        return java.util.Collections.unmodifiableList(fieldValue_);
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public int getFieldValueCount() {
        return fieldValue_.size();
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public java.lang.String getFieldValue(int index) {
        return fieldValue_.get(index);
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public com.google.protobuf.ByteString
          getFieldValueBytes(int index) {
        return fieldValue_.getByteString(index);
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public Builder setFieldValue(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldValueIsMutable();
        fieldValue_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public Builder addFieldValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldValueIsMutable();
        fieldValue_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public Builder addAllFieldValue(
          java.lang.Iterable<java.lang.String> values) {
        ensureFieldValueIsMutable();
        super.addAll(values, fieldValue_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public Builder clearFieldValue() {
        fieldValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_value = 6;</code>
       */
      public Builder addFieldValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldValueIsMutable();
        fieldValue_.add(value);
        onChanged();
        return this;
      }

      // repeated string field_type = 7;
      private com.google.protobuf.LazyStringList fieldType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFieldTypeIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          fieldType_ = new com.google.protobuf.LazyStringArrayList(fieldType_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public java.util.List<java.lang.String>
          getFieldTypeList() {
        return java.util.Collections.unmodifiableList(fieldType_);
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public int getFieldTypeCount() {
        return fieldType_.size();
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public java.lang.String getFieldType(int index) {
        return fieldType_.get(index);
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public com.google.protobuf.ByteString
          getFieldTypeBytes(int index) {
        return fieldType_.getByteString(index);
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public Builder setFieldType(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldTypeIsMutable();
        fieldType_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public Builder addFieldType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldTypeIsMutable();
        fieldType_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public Builder addAllFieldType(
          java.lang.Iterable<java.lang.String> values) {
        ensureFieldTypeIsMutable();
        super.addAll(values, fieldType_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public Builder clearFieldType() {
        fieldType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field_type = 7;</code>
       */
      public Builder addFieldTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldTypeIsMutable();
        fieldType_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gmapper.logic.ToMapperQMsg)
    }

    static {
      defaultInstance = new ToMapperQMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gmapper.logic.ToMapperQMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gmapper_logic_ToMapperQMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gmapper_logic_ToMapperQMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024PBtoMapperQMsg.proto\022\rgmapper.logic\"]\n" +
      "\014ToMapperQMsg\022\020\n\010mapperId\030\004 \002(\005\022\022\n\nfield" +
      "_name\030\005 \003(\t\022\023\n\013field_value\030\006 \003(\t\022\022\n\nfiel" +
      "d_type\030\007 \003(\tB%\n\rgmapper.logicB\024Protobuft" +
      "oMapperQMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gmapper_logic_ToMapperQMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gmapper_logic_ToMapperQMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gmapper_logic_ToMapperQMsg_descriptor,
              new java.lang.String[] { "MapperId", "FieldName", "FieldValue", "FieldType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
